name: "Studio PY SDK"
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    env:
      API_KEY: ${{ secrets.PY_SDK_STAGING_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update system
        run: sudo apt-get update

      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Run pytest
        run: pytest test/test_api.py
